services:
  - type: web
    name: miraio-website
    runtime: static
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=86400
    routes:
      - type: rewrite
        source: /404
        destination: /404.html
